added search path parsing, and exposed methods for search path
CopernicaMarketingSoftware/DNS-CPP pull request #37
Opened 2022-06-24 11:58 UTC by brammel123

This library does not support "search" lines in resolv.conf. ignoring them silencely unless strict mode is on.

In this pull request we just parse the search entries.
In later commits i will add the functionality to actually use the search entries in dns lookups.

2022-06-24 12:25 UTC, EmielBruijntjes requested changes
strings do not stay in scope

2022-06-24 12:25 UTC, EmielBruijntjes commented on src/resolvconf.cpp
> +    _searchpaths.emplace_back(line);
There is no guarentee that line stays in scope, nor that it is null terminated

2022-06-24 12:59 UTC, EmielBruijntjes commented on src/resolvconf.cpp
> +    _searchpaths.emplace_back(line);
Also note that the line itself should also be parsed, as it can contain multiple hostnames

2022-06-28 13:42 UTC, brammel123 commented
strings should stay in scope.
Lines are now seperated on " ".

2022-06-28 13:46 UTC, brammel123 commented on src/resolvconf.cpp
> +    _searchpaths.emplace_back(line);
strings should stay in scope.
Lines are now seperated on " ".

2022-06-28 14:23 UTC, brammel123 commented
should now be threadsafe, respect only the last line, and accept any configuration of spaces and tabs correctly.

2022-06-29 15:12 UTC, merged